# Generated by Django 5.0b1 on 2024-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedBlog', '0002_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default=models.CharField(max_length=150), max_length=150),
        ),
    ]
