# Generated by Django 5.0b1 on 2024-03-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advancedBlog', '0008_post_lieks_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lieks',
            new_name='like',
        ),
    ]
