# Generated by Django 5.0b1 on 2024-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedBlog', '0010_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postFragment',
            field=models.CharField(default='Click title to read post', max_length=400),
        ),
    ]
