# Generated by Django 5.0b1 on 2024-03-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advancedBlog', '0011_post_postfragment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postFragment',
        ),
    ]
