# Generated by Django 5.0.2 on 2024-03-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedBlog', '0015_userprofile_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userInformation',
            new_name='user_information',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profileImage',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
    ]
