# Generated by Django 5.0.2 on 2024-03-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advancedBlog', '0016_rename_userinformation_userprofile_user_information_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
